// AUTOGENERATED FROM template/query.rs.template; DO NOT EDIT DIRECTLY

use std::{collections::BTreeMap, sync::Arc};

use trustfall::{FieldValue, execute_query};

use crate::versioned::VersionedRustdocAdapter;

type QueryResult = BTreeMap<Arc<str>, FieldValue>;

impl<'a> VersionedRustdocAdapter<'a> {
    pub fn run_query<'slf: 'a, K: Into<Arc<str>>, V: Into<FieldValue>>(
        &'slf self,
        query: &str,
        vars: BTreeMap<K, V>,
    ) -> anyhow::Result<Box<dyn Iterator<Item = QueryResult> + 'a>> {
        match self {
            #[cfg(feature = "v55")]
            VersionedRustdocAdapter::V55(_, adapter) => {
                execute_query(self.schema(), Arc::new(adapter), query, vars)
            }

            #[cfg(feature = "v56")]
            VersionedRustdocAdapter::V56(_, adapter) => {
                execute_query(self.schema(), Arc::new(adapter), query, vars)
            }

            #[cfg(feature = "v57")]
            VersionedRustdocAdapter::V57(_, adapter) => {
                execute_query(self.schema(), Arc::new(adapter), query, vars)
            }
        }
    }

    pub fn run_query_with_indexed_query<'slf: 'a, K: Into<Arc<str>>, V: Into<FieldValue>>(
        &'slf self,
        query: Arc<trustfall_core::ir::IndexedQuery>,
        vars: BTreeMap<K, V>,
    ) -> anyhow::Result<Box<dyn Iterator<Item = QueryResult> + 'a>> {
        let vars = Arc::new(
            vars.into_iter()
                .map(|(k, v)| (k.into(), v.into()))
                .collect(),
        );

        match self {
            #[cfg(feature = "v55")]
            VersionedRustdocAdapter::V55(_, adapter) => {
                Ok(trustfall_core::interpreter::execution::interpret_ir(
                    Arc::new(adapter),
                    query,
                    vars,
                )?)
            }

            #[cfg(feature = "v56")]
            VersionedRustdocAdapter::V56(_, adapter) => {
                Ok(trustfall_core::interpreter::execution::interpret_ir(
                    Arc::new(adapter),
                    query,
                    vars,
                )?)
            }

            #[cfg(feature = "v57")]
            VersionedRustdocAdapter::V57(_, adapter) => {
                Ok(trustfall_core::interpreter::execution::interpret_ir(
                    Arc::new(adapter),
                    query,
                    vars,
                )?)
            }
        }
    }
}
